-- Create matches table
create table
  public.matches (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    match_id text not null,
    mode text not null,
    duration interval null,
    creation timestamp with time zone null,
    patch numeric null,
    constraint matches_pkey primary key (id, match_id),
    constraint matches_match_id_key unique (match_id)
  ) tablespace pg_default;

-- Create Participants table (one to many relationship with matches)
create table
  public.participants (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    summoner_id text not null,
    match_id text not null,
    champion text not null,
    kills integer not null,
    assists integer null,
    deaths integer not null,
    win boolean null,
    penta_kills integer null,
    quadra_kills integer null,
    triple_kills integer null,
    spell_1_casts integer null,
    spell_2_casts integer null,
    spell_3_casts integer null,
    spell_4_casts integer null,
    summoner_spell_1_casts integer null,
    summoner_spell_2_casts integer null,
    total_cc_dealt integer null,
    total_damage_dealt_to_champions integer null,
    total_damage_taken integer null,
    total_heal integer null,
    total_minions_killed integer null,
    gold_earned integer null,
    kda numeric null,
    constraint participants_pkey primary key (id),
    constraint unique_participant_combination unique (summoner_id, match_id),
    constraint participants_match_id_fkey foreign key (match_id) references matches (match_id),
    constraint participants_summoner_id_fkey foreign key (summoner_id) references summoners (summoner_id)
  ) tablespace pg_default;

-- Create Summoners table
create table
  public.summoners (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    region text not null,
    puuid text not null,
    account_id text null,
    summoner_id text null,
    summoner_level integer null,
    searchable boolean null default false,
    constraint summoners_pkey primary key (id),
    constraint summoners_puuid_key unique (puuid),
    constraint summoners_summoner_id_key unique (summoner_id)
  ) tablespace pg_default;